### ISSUE TITLE
[建议]关于曲线保证AOD生效方式的思考

### ISSUE THREAD

**Issue by Perpetual-Memories** [Art-Chen/MIUI-Extra-YukiAPI#31]
最新的release，在息屏中直接使用指纹解锁手机后，再次锁屏，则会导致AOD失效；如果在息屏中使用双击亮屏或电源键进入锁屏，则AOD生效。
如果加入一个逻辑，在息屏时按下指纹图标，不进行指纹识别，先从息屏进入锁屏，在进行指纹识别，这种实现方式会更简单一点吗？
当然如果OS2的那套能完整下放肯定更好

**Comment by Art-Chen** [comment]
等OS2吧，效果应该不需要自己实现了
