### ISSUE TITLE
[BUG] 音量条和手势白条的动画无效，后者甚至可能导致系统界面崩溃

### ISSUE THREAD

**Issue by nekOStorm** [Art-Chen/MIUI-Extra-YukiAPI#36]

**Comment by Art-Chen** [comment]
请描述os版本，对应log

**Comment by nekOStorm** [comment]
OS版本：2.0.17.0
日志文件在手机浏览器里难以上传：
https://1drv.ms/u/c/d33abd23e3842b06/ESfTiEo0TxJEiANzPB2DOhIBhbbbbUq0sRt3mQurqYUqUA

**Comment by Art-Chen** [comment]
OS2暂不支持
