### ISSUE TITLE
「也许是个bug」横屏时小白条沉浸会失效

### ISSUE THREAD

**Issue by P1GE0NTV2333** [Art-Chen/MIUI-Extra-YukiAPI#4]
在横屏以及反向竖屏时，小白条不能沉浸

**Comment by Art-Chen** [comment]
https://github.com/Art-Chen/MIUI-Extra-YukiAPI/blob/591b48f1b746b266839711264d233601289583e5/app/src/main/java/moe/chenxy/miuiextra/hooker/entity/systemui/HomeHandleAnimatorHooker.kt#L561-L563

预期行为，本意是为了解决横屏状态下开启增强模式导致的一大片黑问题。当然这个半透明是可以修改成全透明的，不过这样的话使用rro修改更合适。反向竖屏模式Android默认是不激活的 所以不在考虑范围内
