### ISSUE TITLE
[BUG]开启小白条高级材质会导致返回桌面壁纸缩放抽搐

### ISSUE THREAD

**Issue by LumineXiYao** [Art-Chen/MIUI-Extra-YukiAPI#42]
Extra版本r122 OS版本2.0.24.2

**Comment by LumineXiYao** [comment]
https://github.com/user-attachments/assets/f60a89ae-f403-425e-9f53-4ed519bead5b

**Comment by Art-Chen** [comment]
桌面添加到作用域 重启桌面或重启手机后恢复

**Comment by Art-Chen** [comment]
https://github.com/Art-Chen/MIUI-Extra-YukiAPI/commit/614dda8f060b9fe1f7cb170f0914b270ed1c072f
